### ISSUE TITLE
Needs an option to specify port

### ISSUE THREAD

**Issue by bulletmark** [xyproto/teaftp#1]
I have looked around for a simple tftp server program I can run manually to serve files from a directory and teaftp is about all I can find that does that in a simple manner. However, you can not specify a network port to serve files on. This is a problem because it means you must always run teaftp using sudo (because the default port 69 is privileged) which I always prefer to avoid. In short I want to type:

    teaftp -p 8000

rather than:

    sudo teaftp

I am on Arch Linux using teaftp 1.1.1-1 from the AUR.

**Comment by xyproto** [comment]
Thanks for the feature requests. I added new branch named "port" that respects the PORT environment variable. I'm on a boat using my phone right now. The branch needs to have the dependencies updated with "go get -d" and be tested a bit before I can merge it.

**Comment by bulletmark** [comment]
Using an environment variable is one approach, but simply adding a `-p/--port` option is standard for CLI apps. I don't know go but surely that would be easy to do?

**Comment by xyproto** [comment]
Using `PORT` is standard for Go servers and applications that run in the cloud, but if this feature request is specifically about `-p/--port` then that's fine too.

**Comment by xyproto** [comment]
Also, if you're on Linux, you can use: `sudo setcap cap_net_bind_service=+ep /usr/bin/teaftp` to give permissions to `/usr/bin/teaftp` so that it can serve on the TFTP port.

**Comment by xyproto** [comment]
I also added a `Dockerfile` and updated the documentation. It's easy to supply `-ePORT=9000` to the `docker` command line.

TeaFTP can also be launched like this now, on Linux, BSD or macOS:

`PORT=9000 ./teaftp`

I like the idea of keeping `teaftp` as simple as possible and not adding argument parsing.
